// Language translations for ByajBook
export type Language = "en" | "hi"

export const translations = {
  en: {
    // App name
    appName: "ByajBook",
    
    // Dashboard
    totalLent: "Total Lent",
    totalPayable: "Total Payable",
    received: "Received",
    activeLoans: "Active Loans",
    quickActions: "Quick Actions",
    recentLoans: "Recent Loans",
    viewAll: "View All Detail of Loans",
    noLoansYet: "No loans yet. Add your first loan to get started!",
    
    // Actions
    addLoan: "Add Loan",
    addLoanDesc: "Create a new loan entry",
    trackPayments: "Track Payments",
    trackPaymentsDesc: "Record loan payments",
    interestCalculator: "Interest Calculator",
    interestCalculatorDesc: "Calculate interest amounts",
    reports: "Reports",
    reportsDesc: "View summaries and history",
    
    // Interest methods
    monthly: "Monthly",
    yearly: "Yearly",
    sankda: "Sankda",
    
    // Interest types
    simpleInterest: "Simple Interest",
    compoundInterest: "Compound Interest",
    interestType: "Interest Type",
    simpleInterestDesc: "A = P + (P × r × t) / 100",
    compoundInterestDesc: "A = P × (1 + r/100)^t",
    
    // Navigation
    dashboard: "Dashboard",
    loans: "Loans",
    payments: "Payments",
    calculator: "Calculator",
    settings: "Settings",
    home: "Home",
    
    // Settings Page
    security: "Security",
    changePIN: "Change PIN",
    dataManagement: "Data Management",
    exportData: "Export Data (Backup)",
    importData: "Import Data (Restore)",
    appInformation: "App Information",
    version: "Version",
    storage: "Storage",
    totalLoans: "Total Loans",
    totalPayments: "Total Payments",
    privacyData: "Privacy & Data",
    dangerZone: "Danger Zone",
    clearAllData: "Clear All Data",
    logout: "Logout",
    enterCurrentPIN: "Enter Current PIN",
    enterNewPIN: "Enter New PIN",
    confirmNewPIN: "Confirm New PIN",
    enterCurrentPINDesc: "Enter your current 4-digit PIN",
    createNewPINDesc: "Create a new 4-digit PIN",
    confirmNewPINDesc: "Confirm your new 4-digit PIN",
    incorrectPIN: "Incorrect current PIN",
    pinChangedSuccess: "PIN changed successfully",
    pinsDoNotMatch: "PINs do not match",
    clearDataConfirm: "Are you sure you want to clear all data? This action cannot be undone.",
    pinProtection: "Your PIN protects access to all your loan data. Choose a PIN that's easy to remember but hard to guess.",
    dataBackupInfo: "Export your data to create a backup. Import to restore from a previous backup. All data is stored locally on your device.",
    appDescription: "Simple offline-first loan management for personal money lending and interest tracking.",
    dataPrivacyInfo: "Your data is completely private:",
    dataPrivacyPoint1: "All data stored locally on your device",
    dataPrivacyPoint2: "No data sent to external servers",
    dataPrivacyPoint3: "Works completely offline",
    dataPrivacyPoint4: "PIN-protected access",
    dangerZoneInfo: "This will permanently delete all loans, payments, and settings. This action cannot be undone.",
    invalidBackupFile: "Invalid backup file format",
    errorReadingBackup: "Error reading backup file",
    replaceDataConfirm: "This will replace all existing data. Are you sure?",
    dataImportedSuccess: "Data imported successfully",
    localDevice: "Local Device",
    
    // Loans Page
    allLoans: "All Loans",
    add: "Add",
    all: "All",
    active: "Active",
    completed: "Completed",
    noLoansFound: "No loans found",
    noActiveLoansFound: "No active loans found",
    noCompletedLoansFound: "No completed loans found",
    addFirstLoan: "Add Your First Loan",
    loanAmount: "Loan Amount",
    outstanding: "Outstanding",
    interestRate: "Interest Rate",
    dateCreated: "Date Created",
    paymentProgress: "Payment Progress",
    paid: "paid",
    viewDetails: "View Details",
    recordPayment: "Record Payment",
    
    // Add Loan Page
    addNewLoan: "Add New Loan",
    borrowerInformation: "Borrower Information",
    borrowerName: "Borrower Name",
    phoneNumber: "Phone Number",
    notes: "Notes",
    loanDetails: "Loan Details",
    interestMethod: "Interest Method",
    loanPeriod: "Loan Period",
    selectYears: "Select Years",
    validYearsRequired: "Valid loan period is required",
    sankdaDescription: "Sankda method automatically uses 12% yearly interest rate",
    cancel: "Cancel",
    adding: "Adding...",
    borrowerNameRequired: "Borrower name is required",
    validAmountRequired: "Valid loan amount is required",
    validInterestRequired: "Valid interest rate is required",
    validPhoneRequired: "Please enter a valid 10-digit phone number",
    borrowerNamePlaceholder: "Enter borrower's full name",
    phonePlaceholder: "Enter 10-digit phone number",
    notesPlaceholder: "Additional notes about the borrower or loan",
    amountPlaceholder: "Enter loan amount",
    interestPlaceholder: "Enter interest rate",
    yearsPlaceholder: "Enter loan period in years",
    finalPayableAmount: "Final Payable Amount",
    interestAmount: "Interest Amount",
    calculationPreview: "Calculation Preview",
    required: "*",
    
    // Payments Page
    paymentTracking: "Payment Tracking",
    noActiveLoansPayment: "No active loans found",
    recordingPayment: "Recording Payment",
    recentPayments: "Recent Payments",
    noPaymentsRecorded: "No payments recorded yet",
    fullPayment: "Full Payment",
    partialPayment: "Partial Payment",
    unknown: "Unknown",
    paymentSummary: "Payment Summary",
    totalReceived: "Total Received",
    paymentAmount: "Payment Amount",
    validPaymentRequired: "Please enter a valid payment amount",
    paymentExceedsBalance: "Payment amount cannot exceed outstanding balance",
    failedToRecord: "Failed to record payment",
    errorRecordingPayment: "An error occurred while recording payment",
    halfPayment: "Half Payment",
    paymentType: "Payment Type",
    remainingBalance: "Remaining Balance",
    recording: "Recording...",
    totalLoanAmount: "Total Loan Amount",
    pendingAmount: "Pending Amount",
    finalAmount: "Final Amount",
    lastPayment: "Last Payment",
    noPaymentsYet: "No payments yet",
    
    // Calculator Page
    calculateInterest: "Calculate Interest",
    principalAmount: "Principal Amount",
    calculationMethod: "Calculation Method",
    monthlyInterest: "Monthly Interest",
    yearlyInterest: "Yearly Interest (Simple)",
    sankdaFixed: "Sankda (12% yearly)",
    sankdaMethodInfo: "Sankda method uses a fixed 12% yearly interest rate",
    timePeriod: "Time Period",
    unit: "Unit",
    months: "Months",
    years: "Years",
    calculate: "Calculate",
    reset: "Reset",
    calculationResults: "Calculation Results",
    totalInterest: "Total Interest",
    totalAmount: "Total Amount",
    effectiveRate: "Effective Rate",
    monthlyInterestLabel: "Monthly Interest",
    methodExplanation: "Calculation Method:",
    monthlyExplanation: "Monthly interest is calculated as a fixed percentage of the principal amount each month.",
    yearlyExplanation: "Yearly interest uses simple interest formula: (Principal × Rate × Time) / 100",
    sankdaExplanation: "Sankda method applies 12% yearly interest, typically calculated monthly for traditional lending.",
    compoundExplanation: "Compound interest is calculated on the principal amount plus previously earned interest.",
    quickExamples: "Quick Examples",
    interest: "interest",
    enterPrincipalAmount: "Enter principal amount",
    enterInterestRate: "Enter interest rate",
    enterTime: "Enter time",
    validPrincipalRequired: "Valid principal amount is required",
    validTimeRequired: "Valid time period is required",
    
    // Reports Page
    reportsAnalytics: "Reports & Analytics",
    summaryCards: "Summary",
    interestAnalysis: "Interest Analysis",
    estimatedInterestEarned: "Estimated Interest Earned",
    potentialInterest: "Potential Interest",
    collectionRate: "Collection Rate",
    potentialInterestCollected: "of potential interest collected",
    monthlyTrends: "Monthly Trends (Last 12 Months)",
    lent: "Lent",
    borrowerWiseSummary: "Borrower-wise Summary",
    noBorrowerData: "No borrower data available",
    recoveryRate: "Recovery Rate",
    recentActivity: "Recent Activity",
    loanCreated: "Loan created",
    paymentReceived: "Payment received",
    
    // Common
    back: "Back",
    save: "Save",
    close: "Close",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    edit: "Edit",
    delete: "Delete",
    deleteLoan: "Delete Loan",
    deleteLoanConfirm: "Are you sure you want to delete this loan? This action cannot be undone and will also remove all associated payment records.",
    loanDeleted: "Loan deleted successfully",
    failedToDeleteLoan: "Failed to delete loan",
    
    // Edit Loan
    editLoan: "Edit Loan",
    updateLoan: "Update Loan",
    updating: "Updating...",
    loanNotFound: "Loan not found",
    failedToUpdateLoan: "Failed to update loan",
    errorUpdatingLoan: "Error updating loan",

    // Due Date & Reminders
    dueDate: "Due Date",
    dueDateRequired: "Due date is required",
    selectDueDate: "Select due date",
    dueReminders: "Due Reminders",
    reminderSettings: "Reminder Settings",
    reminderDays: "Reminder Days",
    enableReminders: "Enable Reminders",
    showRemindersBefore: "Show reminders before due date",
    day: "day",
    days: "days",
    dueToday: "Due Today",
    dueIn: "Due in",
    overdue: "Overdue",
    overdueBy: "Overdue by",
    noReminders: "No reminders at this time",
    reminderFor: "Reminder for",
    loanDueReminder: "Loan Due Reminder",
  },
  hi: {
    // App name
    appName: "ब्याजबुक",
    
    // Dashboard
    totalLent: "कुल दिया गया",
    totalPayable: "कुल देय",
    received: "प्राप्त",
    activeLoans: "सक्रिय ऋण",
    quickActions: "त्वरित कार्य",
    recentLoans: "हाल के ऋण",
    viewAll: "ऋणों का सम्पूर्ण विवरण देखें",
    noLoansYet: "अभी तक कोई ऋण नहीं। शुरुआत करने के लिए अपना पहला ऋण जोड़ें!",
    
    // Actions
    addLoan: "ऋण जोड़ें",
    addLoanDesc: "नई ऋण प्रविष्टि बनाएं",
    trackPayments: "भुगतान ट्रैक करें",
    trackPaymentsDesc: "ऋण भुगतान रिकॉर्ड करें",
    interestCalculator: "ब्याज कैलकुलेटर",
    interestCalculatorDesc: "ब्याज राशि की गणना करें",
    reports: "रिपोर्ट",
    reportsDesc: "सारांश और इतिहास देखें",
    
    // Interest methods
    monthly: "मासिक",
    yearly: "वार्षिक",
    sankda: "संकड़ा",
    
    // Interest types
    simpleInterest: "साधारण ब्याज",
    compoundInterest: "चक्रवृद्धि ब्याज",
    interestType: "ब्याज प्रकार",
    simpleInterestDesc: "A = P + (P × r × t) / 100",
    compoundInterestDesc: "A = P × (1 + r/100)^t",
    
    // Navigation
    dashboard: "डैशबोर्ड",
    loans: "ऋण",
    payments: "भुगतान",
    calculator: "कैलकुलेटर",
    settings: "सेटिंग्स",
    home: "होम",
    
    // Settings Page
    security: "सुरक्षा",
    changePIN: "पिन बदलें",
    dataManagement: "डेटा प्रबंधन",
    exportData: "डेटा निर्यात (बैकअप)",
    importData: "डेटा आयात (पुनर्स्थापना)",
    appInformation: "ऐप जानकारी",
    version: "संस्करण",
    storage: "स्टोरेज",
    totalLoans: "कुल ऋण",
    totalPayments: "कुल भुगतान",
    privacyData: "गोपनीयता और डेटा",
    dangerZone: "खतरनाक क्षेत्र",
    clearAllData: "सभी डेटा साफ़ करें",
    logout: "लॉगआउट",
    enterCurrentPIN: "वर्तमान पिन दर्ज करें",
    enterNewPIN: "नया पिन दर्ज करें",
    confirmNewPIN: "नए पिन की पुष्टि करें",
    enterCurrentPINDesc: "अपना वर्तमान 4-अंकीय पिन दर्ज करें",
    createNewPINDesc: "एक नया 4-अंकीय पिन बनाएं",
    confirmNewPINDesc: "अपने नए 4-अंकीय पिन की पुष्टि करें",
    incorrectPIN: "गलत वर्तमान पिन",
    pinChangedSuccess: "पिन सफलतापूर्वक बदल दिया गया",
    pinsDoNotMatch: "पिन मेल नहीं खाते",
    clearDataConfirm: "क्या आप वाकई सभी डेटा साफ़ करना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
    pinProtection: "आपका पिन आपके सभी ऋण डेटा तक पहुंच की सुरक्षा करता है। ऐसा पिन चुनें जो याद रखना आसान हो लेकिन अनुमान लगाना कठिन हो।",
    dataBackupInfo: "बैकअप बनाने के लिए अपने डेटा को निर्यात करें। पिछले बैकअप से पुनर्स्थापित करने के लिए आयात करें। सभी डेटा आपके डिवाइस पर स्थानीय रूप से संग्रहीत है।",
    appDescription: "व्यक्तिगत पैसे उधार देने और ब्याज ट्रैकिंग के लिए सरल ऑफ़लाइन-फर्स्ट ऋण प्रबंधन।",
    dataPrivacyInfo: "आपका डेटा पूर्णतः निजी है:",
    dataPrivacyPoint1: "सभी डेटा आपके डिवाइस पर स्थानीय रूप से संग्रहीत",
    dataPrivacyPoint2: "बाहरी सर्वर को कोई डेटा नहीं भेजा जाता",
    dataPrivacyPoint3: "पूर्णतः ऑफ़लाइन काम करता है",
    dataPrivacyPoint4: "पिन-संरक्षित पहुंच",
    dangerZoneInfo: "इससे सभी ऋण, भुगतान और सेटिंग्स स्थायी रूप से हटा दिए जाएंगे। यह क्रिया पूर्ववत नहीं की जा सकती।",
    invalidBackupFile: "अमान्य बैकअप फ़ाइल फॉर्मेट",
    errorReadingBackup: "बैकअप फ़ाइल पढ़ने में त्रुटि",
    replaceDataConfirm: "इससे सभी मौजूदा डेटा बदल जाएगा। क्या आप निश्चित हैं?",
    dataImportedSuccess: "डेटा सफलतापूर्वक आयात किया गया",
    localDevice: "स्थानीय डिवाइस",
    
    // Loans Page
    allLoans: "सभी ऋण",
    add: "जोड़ें",
    all: "सभी",
    active: "सक्रिय",
    completed: "पूर्ण",
    noLoansFound: "कोई ऋण नहीं मिला",
    noActiveLoansFound: "कोई सक्रिय ऋण नहीं मिला",
    noCompletedLoansFound: "कोई पूर्ण ऋण नहीं मिला",
    addFirstLoan: "अपना पहला ऋण जोड़ें",
    loanAmount: "ऋण राशि",
    outstanding: "बकाया",
    interestRate: "ब्याज दर",
    dateCreated: "निर्माण तिथि",
    paymentProgress: "भुगतान प्रगति",
    paid: "भुगतान",
    viewDetails: "विवरण देखें",
    recordPayment: "भुगतान रिकॉर्ड करें",
    
    // Add Loan Page
    addNewLoan: "नया ऋण जोड़ें",
    borrowerInformation: "उधारकर्ता की जानकारी",
    borrowerName: "उधारकर्ता का नाम",
    phoneNumber: "फ़ोन नंबर",
    notes: "टिप्पणियां",
    loanDetails: "ऋण विवरण",
    interestMethod: "ब्याज विधि",
    loanPeriod: "ऋण अवधि",
    selectYears: "वर्ष चुनें",
    validYearsRequired: "वैध ऋण अवधि आवश्यक है",
    sankdaDescription: "संकड़ा विधि स्वचालित रूप से 12% वार्षिक ब्याज दर का उपयोग करती है",
    cancel: "रद्द करें",
    adding: "जोड़ा जा रहा है...",
    borrowerNameRequired: "उधारकर्ता का नाम आवश्यक है",
    validAmountRequired: "वैध ऋण राशि आवश्यक है",
    validInterestRequired: "वैध ब्याज दर आवश्यक है",
    validPhoneRequired: "कृपया वैध 10-अंकीय फ़ोन नंबर दर्ज करें",
    borrowerNamePlaceholder: "उधारकर्ता का पूरा नाम दर्ज करें",
    phonePlaceholder: "10-अंकीय फ़ोन नंबर दर्ज करें",
    notesPlaceholder: "उधारकर्ता या ऋण के बारे में अतिरिक्त टिप्पणियां",
    amountPlaceholder: "ऋण राशि दर्ज करें",
    interestPlaceholder: "ब्याज दर दर्ज करें",
    yearsPlaceholder: "वर्षों में ऋण अवधि दर्ज करें",
    finalPayableAmount: "अंतिम देय राशि",
    interestAmount: "ब्याज राशि",
    calculationPreview: "गणना पूर्वावलोकन",
    required: "*",
    
    // Payments Page
    paymentTracking: "भुगतान ट्रैकिंग",
    noActiveLoansPayment: "कोई सक्रिय ऋण नहीं मिला",
    recordingPayment: "भुगतान रिकॉर्ड करना",
    recentPayments: "हाल के भुगतान",
    noPaymentsRecorded: "अभी तक कोई भुगतान रिकॉर्ड नहीं किया गया",
    fullPayment: "पूर्ण भुगतान",
    partialPayment: "आंशिक भुगतान",
    unknown: "अज्ञात",
    paymentSummary: "भुगतान सारांश",
    totalReceived: "कुल प्राप्त",
    paymentAmount: "भुगतान राशि",
    validPaymentRequired: "कृपया वैध भुगतान राशि दर्ज करें",
    paymentExceedsBalance: "भुगतान राशि बकाया राशि से अधिक नहीं हो सकती",
    failedToRecord: "भुगतान रिकॉर्ड करने में विफल",
    errorRecordingPayment: "भुगतान रिकॉर्ड करते समय त्रुटि हुई",
    halfPayment: "आधा भुगतान",
    paymentType: "भुगतान प्रकार",
    remainingBalance: "शेष राशि",
    recording: "रिकॉर्ड कर रहे हैं...",
    totalLoanAmount: "कुल ऋण राशि",
    pendingAmount: "बकाया राशि",
    finalAmount: "अंतिम राशि",
    lastPayment: "अंतिम भुगतान",
    noPaymentsYet: "अभी तक कोई भुगतान नहीं",
    
    // Calculator Page
    calculateInterest: "ब्याज की गणना करें",
    principalAmount: "मूल राशि",
    calculationMethod: "गणना विधि",
    monthlyInterest: "मासिक ब्याज",
    yearlyInterest: "वार्षिक ब्याज (सामान्य)",
    sankdaFixed: "संकड़ा (12% वार्षिक)",
    sankdaMethodInfo: "संकड़ा विधि एक निश्चित 12% वार्षिक ब्याज दर का उपयोग करती है",
    timePeriod: "समय अवधि",
    unit: "इकाई",
    months: "महीने",
    years: "वर्ष",
    calculate: "गणना करें",
    reset: "रीसेट",
    calculationResults: "गणना परिणाम",
    totalInterest: "कुल ब्याज",
    totalAmount: "कुल राशि",
    effectiveRate: "प्रभावी दर",
    monthlyInterestLabel: "मासिक ब्याज",
    methodExplanation: "गणना विधि:",
    monthlyExplanation: "मासिक ब्याज को मूल राशि के एक निश्चित प्रतिशत के रूप में प्रत्येक माह की गणना की जाती है।",
    yearlyExplanation: "वार्षिक ब्याज सामान्य ब्याज फॉर्मूला का उपयोग करता है: (मूल × दर × समय) / 100",
    sankdaExplanation: "संकड़ा विधि 12% वार्षिक ब्याज लागू करती है, आमतौर पर पारंपरिक उधार देने के लिए मासिक गणना की जाती है।",
    compoundExplanation: "चक्रवृद्धि ब्याज मूल राशि और पहले अर्जित ब्याज पर गणना की जाती है।",
    quickExamples: "त्वरित उदाहरण",
    interest: "ब्याज",
    enterPrincipalAmount: "मूल राशि दर्ज करें",
    enterInterestRate: "ब्याज दर दर्ज करें",
    enterTime: "समय दर्ज करें",
    validPrincipalRequired: "वैध मूल राशि आवश्यक है",
    validTimeRequired: "वैध समय अवधि आवश्यक है",
    
    // Reports Page
    reportsAnalytics: "रिपोर्ट और विश्लेषण",
    summaryCards: "सारांश",
    interestAnalysis: "ब्याज विश्लेषण",
    estimatedInterestEarned: "अनुमानित ब्याज अर्जित",
    potentialInterest: "संभावित ब्याज",
    collectionRate: "संग्रह दर",
    potentialInterestCollected: "संभावित ब्याज का संग्रह",
    monthlyTrends: "मासिक रुझान (पिछले 12 महीने)",
    lent: "दिया गया",
    borrowerWiseSummary: "उधारकर्ता-वार सारांश",
    noBorrowerData: "कोई उधारकर्ता डेटा उपलब्ध नहीं",
    recoveryRate: "वसूली दर",
    recentActivity: "हाल की गतिविधि",
    loanCreated: "ऋण बनाया गया",
    paymentReceived: "भुगतान प्राप्त",
    
    // Common
    back: "वापस",
    save: "सहेजें",
    close: "बंद करें",
    confirm: "पुष्टि करें",
    yes: "हां",
    no: "नहीं",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    warning: "चेतावनी",
    info: "जानकारी",
    edit: "संपादित करें",
    delete: "हटाएं",
    deleteLoan: "ऋण हटाएं",
    deleteLoanConfirm: "क्या आप वाकई इस ऋण को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती और इससे सभी संबंधित भुगतान रिकॉर्ड भी हटा दिए जाएंगे।",
    loanDeleted: "ऋण सफलतापूर्वक हटा दिया गया",
    failedToDeleteLoan: "ऋण हटाने में असफल",
    
    // Edit Loan
    editLoan: "ऋण संपादित करें",
    updateLoan: "ऋण अपडेट करें",
    updating: "अपडेट कर रहे हैं...",
    loanNotFound: "ऋण नहीं मिला",
    failedToUpdateLoan: "ऋण अपडेट करने में असफल",
    errorUpdatingLoan: "ऋण अपडेट करने में त्रुटि",

    // Due Date & Reminders
    dueDate: "देय तिथि",
    dueDateRequired: "देय तिथि आवश्यक है",
    selectDueDate: "देय तिथि चुनें",
    dueReminders: "देय रिमाइंडर",
    reminderSettings: "रिमाइंडर सेटिंग्स",
    reminderDays: "रिमाइंडर दिन",
    enableReminders: "रिमाइंडर सक्षम करें",
    showRemindersBefore: "देय तिथि से पहले रिमाइंडर दिखाएं",
    day: "दिन",
    days: "दिन",
    dueToday: "आज देय",
    dueIn: "देय है",
    overdue: "अतिदेय",
    overdueBy: "से अतिदेय",
    noReminders: "इस समय कोई रिमाइंडर नहीं",
    reminderFor: "के लिए रिमाइंडर",
    loanDueReminder: "ऋण देय रिमाइंडर",
  },
} as const

export function getTranslation(language: Language, key: keyof typeof translations.en): string {
  return translations[language][key] || translations.en[key]
}
